export const GET_COURSE_LIST_ADMIN = "GET_COURSE_LIST_ADMIN";
export const GET_COURSE_LIST_ADMIN_SAGA = "GET_COURSE_LIST_ADMIN_SAGA";

export const ADD_COURSE_ADMIN = "ADD_COURSE_ADMIN";
export const ADD_COURSE_ADMIN_SAGA = "ADD_COURSE_ADMIN_SAGA";

export const ADD_COURSE_IMAGE_ADMIN = "ADD_COURSE_IMAGE_ADMIN";
export const ADD_COURSE_IMAGE_ADMIN_SAGA = "ADD_COURSE_IMAGE_ADMIN_SAGA";

export const UPDATE_COURSE_IMAGE_ADMIN = "UPDATE_COURSE_IMAGE_ADMIN";
export const UPDATE_COURSE_IMAGE_ADMIN_SAGA = "UPDATE_COURSE_IMAGE_ADMIN_SAGA";

export const DELETE_COURSE_ADMIN = "DELETE_COURSE_ADMIN";
export const DELETE_COURSE_ADMIN_SAGA = "DELETE_COURSE_ADMIN_SAGA";
