export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_SAGA = "GET_USER_LIST_SAGA";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SAGA = "EDIT_USER_SAGA";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SAGA = "DELETE_USER_SAGA";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SAGA = "ADD_USER_SAGA";

export const VIEW_PROFILE_USER = "VIEW_PROFILE_USER";
export const VIEW_PROFILE_USER_SAGA = "VIEW_PROFILE_USER_SAGA";
