export const UNREGISTER_COURSE = "UNREGISTER_COURSE";
export const UNREGISTER_COURSE_SAGA = "UNREGISTER_COURSE_SAGA";

export const REGISTER_COURSE = "REGISTER_COURSE";
export const REGISTER_COURSE_SAGA = "REGISTER_COURSE_SAGA";
