export const BOOKING_COURSE = "BOOKING_COURSE";
export const BOOKING_COURSE_SAGA = "BOOKING_COURSE_SAGA";

export const UNBOOKING_COURSE = "UNBOOKING_COURSE";
export const UNBOOKING_COURSE_SAGA = "UNBOOKING_COURSE_SAGA";
